ALTER TABLE topics
MODIFY titulo VARCHAR(255) NOT NULL UNIQUE;

ALTER TABLE topics
MODIFY mensaje VARCHAR(255) NOT NULL UNIQUE;

ALTER TABLE topics
MODIFY fecha DATETIME NOT NULL;

ALTER TABLE topics
MODIFY status VARCHAR(255) NOT NULL;

ALTER TABLE topics
MODIFY id_usuario BIGINT NOT NULL;

ALTER TABLE topics
MODIFY curso VARCHAR(255) NOT NULL;

